<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Tests;

use Core\Types\CallbackCatcher;
use MistAPILib\Authentication\ApiTokenCredentialsBuilder;
use MistAPILib\Authentication\BasicAuthCredentialsBuilder;
use MistAPILib\Authentication\CsrfTokenCredentialsBuilder;
use MistAPILib\MistAPIClient;
use MistAPILib\MistAPIClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): MistAPIClient
    {
        $clientBuilder = MistAPIClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(MistAPIClientBuilder $builder): MistAPIClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(MistAPIClientBuilder $builder): MistAPIClientBuilder
    {
        $timeout = getenv('MIST_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('MIST_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('MIST_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('MIST_API_LIB_ENVIRONMENT');
        $authorization = getenv('MIST_API_LIB_AUTHORIZATION');
        $username = getenv('MIST_API_LIB_USERNAME');
        $password = getenv('MIST_API_LIB_PASSWORD');
        $xCSRFToken = getenv('MIST_API_LIB_X_CSRF_TOKEN');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($authorization)) {
            $builder->apiTokenCredentials(ApiTokenCredentialsBuilder::init($authorization));
        }

        if (!empty($username) && !empty($password)) {
            $builder->basicAuthCredentials(BasicAuthCredentialsBuilder::init($username, $password));
        }

        if (!empty($xCSRFToken)) {
            $builder->csrfTokenCredentials(CsrfTokenCredentialsBuilder::init($xCSRFToken));
        }

        return $builder;
    }
}
