<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ApiTokenCredentials
{
    /**
     * String value for authorization.
     */
    public function getAuthorization(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Like many other API providers, itâ€™s also possible to generate
     *        API Tokens to be used (in HTTP Header) for authentication. An API token ties to a
     *        Admin with equal or less privileges.
     *
     *        **Format**:
     *        API Token value format is `Token {apitoken}`
     *
     *        **Notes**:
     *        * an API token generated for a specific admin has the same privilege as the user
     *        * an API token will be automatically removed if not used for > 90 days
     *        * SSO admins cannot generate these API tokens. Refer Org level API tokens which can
     *        have privileges of a specific Org/Site for more information.
     */
    public function equals(string $authorization): bool;
}
