<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface CsrfTokenCredentials
{
    /**
     * String value for xCSRFToken.
     */
    public function getXCSRFToken(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $xCSRFToken This protects the website against [Cross Site Request
     *        Forgery](http://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST /
     *        PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using
     *        Login/Password authentication (with or without MFA)
     *
     *
     *        The CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:
     *        `cookies[csrftoken]`
     *
     *        The CSRF Token must be added in the HTTP Request Headers:
     *        ```
     *        X-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx
     *        ```
     */
    public function equals(string $xCSRFToken): bool;
}
