<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing CsrfToken security credentials.
 */
class CsrfTokenCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for CsrfTokenCredentialsBuilder
     *
     * @param string $xCSRFToken
     */
    public static function init(string $xCSRFToken): self
    {
        return new self(['xCSRFToken' => $xCSRFToken]);
    }

    /**
     * Setter for XCSRFToken.
     *
     * @param string $xCSRFToken
     *
     * @return $this
     */
    public function xCSRFToken(string $xCSRFToken): self
    {
        $this->config['xCSRFToken'] = $xCSRFToken;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
