<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\NacCrlFile;

/**
 * Builder for model NacCrlFile
 *
 * @see NacCrlFile
 */
class NacCrlFileBuilder
{
    /**
     * @var NacCrlFile
     */
    private $instance;

    private function __construct(NacCrlFile $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new nac crl file Builder object.
     */
    public static function init(): self
    {
        return new self(new NacCrlFile());
    }

    /**
     * Sets created time field.
     */
    public function createdTime(?float $value): self
    {
        $this->instance->setCreatedTime($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets modified time field.
     */
    public function modifiedTime(?float $value): self
    {
        $this->instance->setModifiedTime($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets url field.
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new nac crl file object.
     */
    public function build(): NacCrlFile
    {
        return CoreHelper::clone($this->instance);
    }
}
