<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\NacPortalTemplate;

/**
 * Builder for model NacPortalTemplate
 *
 * @see NacPortalTemplate
 */
class NacPortalTemplateBuilder
{
    /**
     * @var NacPortalTemplate
     */
    private $instance;

    private function __construct(NacPortalTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new nac portal template Builder object.
     */
    public static function init(): self
    {
        return new self(new NacPortalTemplate());
    }

    /**
     * Sets alignment field.
     */
    public function alignment(?string $value): self
    {
        $this->instance->setAlignment($value);
        return $this;
    }

    /**
     * Sets color field.
     */
    public function color(?string $value): self
    {
        $this->instance->setColor($value);
        return $this;
    }

    /**
     * Sets logo field.
     */
    public function logo(?string $value): self
    {
        $this->instance->setLogo($value);
        return $this;
    }

    /**
     * Sets powered by field.
     */
    public function poweredBy(?bool $value): self
    {
        $this->instance->setPoweredBy($value);
        return $this;
    }

    /**
     * Initializes a new nac portal template object.
     */
    public function build(): NacPortalTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
