<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\NacTag;

/**
 * Builder for model NacTag
 *
 * @see NacTag
 */
class NacTagBuilder
{
    /**
     * @var NacTag
     */
    private $instance;

    private function __construct(NacTag $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new nac tag Builder object.
     */
    public static function init(string $name, string $type): self
    {
        return new self(new NacTag($name, $type));
    }

    /**
     * Sets allow usermac override field.
     */
    public function allowUsermacOverride(?bool $value): self
    {
        $this->instance->setAllowUsermacOverride($value);
        return $this;
    }

    /**
     * Sets created time field.
     */
    public function createdTime(?float $value): self
    {
        $this->instance->setCreatedTime($value);
        return $this;
    }

    /**
     * Sets egress vlan names field.
     */
    public function egressVlanNames(?array $value): self
    {
        $this->instance->setEgressVlanNames($value);
        return $this;
    }

    /**
     * Sets gbp tag field.
     */
    public function gbpTag(?int $value): self
    {
        $this->instance->setGbpTag($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets match field.
     */
    public function match(?string $value): self
    {
        $this->instance->setMatch($value);
        return $this;
    }

    /**
     * Sets match all field.
     */
    public function matchAll(?bool $value): self
    {
        $this->instance->setMatchAll($value);
        return $this;
    }

    /**
     * Sets modified time field.
     */
    public function modifiedTime(?float $value): self
    {
        $this->instance->setModifiedTime($value);
        return $this;
    }

    /**
     * Sets org id field.
     */
    public function orgId(?string $value): self
    {
        $this->instance->setOrgId($value);
        return $this;
    }

    /**
     * Sets radius attrs field.
     */
    public function radiusAttrs(?array $value): self
    {
        $this->instance->setRadiusAttrs($value);
        return $this;
    }

    /**
     * Sets radius group field.
     */
    public function radiusGroup(?string $value): self
    {
        $this->instance->setRadiusGroup($value);
        return $this;
    }

    /**
     * Sets radius vendor attrs field.
     */
    public function radiusVendorAttrs(?array $value): self
    {
        $this->instance->setRadiusVendorAttrs($value);
        return $this;
    }

    /**
     * Sets session timeout field.
     */
    public function sessionTimeout(?int $value): self
    {
        $this->instance->setSessionTimeout($value);
        return $this;
    }

    /**
     * Sets username attr field.
     */
    public function usernameAttr(?string $value): self
    {
        $this->instance->setUsernameAttr($value);
        return $this;
    }

    /**
     * Sets values field.
     */
    public function values(?array $value): self
    {
        $this->instance->setValues($value);
        return $this;
    }

    /**
     * Sets vlan field.
     */
    public function vlan(?string $value): self
    {
        $this->instance->setVlan($value);
        return $this;
    }

    /**
     * Initializes a new nac tag object.
     */
    public function build(): NacTag
    {
        return CoreHelper::clone($this->instance);
    }
}
