<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\NameString;

/**
 * Builder for model NameString
 *
 * @see NameString
 */
class NameStringBuilder
{
    /**
     * @var NameString
     */
    private $instance;

    private function __construct(NameString $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new name string Builder object.
     */
    public static function init(): self
    {
        return new self(new NameString());
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new name string object.
     */
    public function build(): NameString
    {
        return CoreHelper::clone($this->instance);
    }
}
