<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\NetworkDestinationNatProperty;

/**
 * Builder for model NetworkDestinationNatProperty
 *
 * @see NetworkDestinationNatProperty
 */
class NetworkDestinationNatPropertyBuilder
{
    /**
     * @var NetworkDestinationNatProperty
     */
    private $instance;

    private function __construct(NetworkDestinationNatProperty $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new network destination nat property Builder object.
     */
    public static function init(): self
    {
        return new self(new NetworkDestinationNatProperty());
    }

    /**
     * Sets internal ip field.
     */
    public function internalIp(?string $value): self
    {
        $this->instance->setInternalIp($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets port field.
     */
    public function port(?int $value): self
    {
        $this->instance->setPort($value);
        return $this;
    }

    /**
     * Initializes a new network destination nat property object.
     */
    public function build(): NetworkDestinationNatProperty
    {
        return CoreHelper::clone($this->instance);
    }
}
