<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\NetworkStaticNatProperty;

/**
 * Builder for model NetworkStaticNatProperty
 *
 * @see NetworkStaticNatProperty
 */
class NetworkStaticNatPropertyBuilder
{
    /**
     * @var NetworkStaticNatProperty
     */
    private $instance;

    private function __construct(NetworkStaticNatProperty $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new network static nat property Builder object.
     */
    public static function init(): self
    {
        return new self(new NetworkStaticNatProperty());
    }

    /**
     * Sets internal ip field.
     */
    public function internalIp(?string $value): self
    {
        $this->instance->setInternalIp($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets wan name field.
     */
    public function wanName(?string $value): self
    {
        $this->instance->setWanName($value);
        return $this;
    }

    /**
     * Initializes a new network static nat property object.
     */
    public function build(): NetworkStaticNatProperty
    {
        return CoreHelper::clone($this->instance);
    }
}
