<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\ResponseSsoFailureSearch;

/**
 * Builder for model ResponseSsoFailureSearch
 *
 * @see ResponseSsoFailureSearch
 */
class ResponseSsoFailureSearchBuilder
{
    /**
     * @var ResponseSsoFailureSearch
     */
    private $instance;

    private function __construct(ResponseSsoFailureSearch $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new response sso failure search Builder object.
     */
    public static function init(array $results): self
    {
        return new self(new ResponseSsoFailureSearch($results));
    }

    /**
     * Initializes a new response sso failure search object.
     */
    public function build(): ResponseSsoFailureSearch
    {
        return CoreHelper::clone($this->instance);
    }
}
