<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use MistAPILib\Models\ResponseSsoFailureSearchItem;

/**
 * Builder for model ResponseSsoFailureSearchItem
 *
 * @see ResponseSsoFailureSearchItem
 */
class ResponseSsoFailureSearchItemBuilder
{
    /**
     * @var ResponseSsoFailureSearchItem
     */
    private $instance;

    private function __construct(ResponseSsoFailureSearchItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new response sso failure search item Builder object.
     */
    public static function init(string $detail, string $samlAssertionXml, float $timestamp): self
    {
        return new self(new ResponseSsoFailureSearchItem($detail, $samlAssertionXml, $timestamp));
    }

    /**
     * Initializes a new response sso failure search item object.
     */
    public function build(): ResponseSsoFailureSearchItem
    {
        return CoreHelper::clone($this->instance);
    }
}
