<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models;

use stdClass;

class NacCrlFile implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $createdTime;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var float|null
     */
    private $modifiedTime;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $url;

    /**
     * Returns Created Time.
     * Time at which the file was first uploaded, in epoch
     */
    public function getCreatedTime(): ?float
    {
        return $this->createdTime;
    }

    /**
     * Sets Created Time.
     * Time at which the file was first uploaded, in epoch
     *
     * @maps created_time
     */
    public function setCreatedTime(?float $createdTime): void
    {
        $this->createdTime = $createdTime;
    }

    /**
     * Returns Id.
     * ID for file upload, used to identify file even for deletion
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * ID for file upload, used to identify file even for deletion
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Modified Time.
     * Time at which the file was last updated, in epoch
     */
    public function getModifiedTime(): ?float
    {
        return $this->modifiedTime;
    }

    /**
     * Sets Modified Time.
     * Time at which the file was last updated, in epoch
     *
     * @maps modified_time
     */
    public function setModifiedTime(?float $modifiedTime): void
    {
        $this->modifiedTime = $modifiedTime;
    }

    /**
     * Returns Name.
     * Name for the .crl file issuer if set
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name for the .crl file issuer if set
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Url.
     * Download URL for the .crl file
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * Download URL for the .crl file
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->createdTime)) {
            $json['created_time']  = $this->createdTime;
        }
        if (isset($this->id)) {
            $json['id']            = $this->id;
        }
        if (isset($this->modifiedTime)) {
            $json['modified_time'] = $this->modifiedTime;
        }
        if (isset($this->name)) {
            $json['name']          = $this->name;
        }
        if (isset($this->url)) {
            $json['url']           = $this->url;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
