<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models;

use stdClass;

class NacPortalSsoRoleMatching implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $assigned;

    /**
     * @var string|null
     */
    private $match;

    /**
     * Returns Assigned.
     */
    public function getAssigned(): ?string
    {
        return $this->assigned;
    }

    /**
     * Sets Assigned.
     *
     * @maps assigned
     */
    public function setAssigned(?string $assigned): void
    {
        $this->assigned = $assigned;
    }

    /**
     * Returns Match.
     */
    public function getMatch(): ?string
    {
        return $this->match;
    }

    /**
     * Sets Match.
     *
     * @maps match
     */
    public function setMatch(?string $match): void
    {
        $this->match = $match;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->assigned)) {
            $json['assigned'] = $this->assigned;
        }
        if (isset($this->match)) {
            $json['match']    = $this->match;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
