<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * if `type`==`match`. enum: `cert_cn`, `cert_issuer`, `cert_san`, `cert_serial`, `cert_sub`,
 * `client_mac`, `idp_role`, `mdm_status`, `radius_group`, `realm`, `ssid`, `user_name`,
 * `usermac_label`
 */
class NacTagMatchEnum
{
    public const CERT_CN = 'cert_cn';

    public const CERT_ISSUER = 'cert_issuer';

    public const CERT_SAN = 'cert_san';

    public const CERT_SERIAL = 'cert_serial';

    public const CERT_SUB = 'cert_sub';

    public const CLIENT_MAC = 'client_mac';

    public const IDP_ROLE = 'idp_role';

    public const MDM_STATUS = 'mdm_status';

    public const RADIUS_GROUP = 'radius_group';

    public const REALM = 'realm';

    public const SSID = 'ssid';

    public const USER_NAME = 'user_name';

    public const USERMAC_LABEL = 'usermac_label';

    private const _ALL_VALUES = [
        self::CERT_CN,
        self::CERT_ISSUER,
        self::CERT_SAN,
        self::CERT_SERIAL,
        self::CERT_SUB,
        self::CLIENT_MAC,
        self::IDP_ROLE,
        self::MDM_STATUS,
        self::RADIUS_GROUP,
        self::REALM,
        self::SSID,
        self::USER_NAME,
        self::USERMAC_LABEL
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for NacTagMatchEnum.");
    }
}
