<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models;

use stdClass;

class NetworkDestinationNatProperty implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $internalIp;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var int|null
     */
    private $port;

    /**
     * Returns Internal Ip.
     */
    public function getInternalIp(): ?string
    {
        return $this->internalIp;
    }

    /**
     * Sets Internal Ip.
     *
     * @maps internal_ip
     */
    public function setInternalIp(?string $internalIp): void
    {
        $this->internalIp = $internalIp;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Port.
     */
    public function getPort(): ?int
    {
        return $this->port;
    }

    /**
     * Sets Port.
     *
     * @maps port
     */
    public function setPort(?int $port): void
    {
        $this->port = $port;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->internalIp)) {
            $json['internal_ip'] = $this->internalIp;
        }
        if (isset($this->name)) {
            $json['name']        = $this->name;
        }
        if (isset($this->port)) {
            $json['port']        = $this->port;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
