<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models;

use stdClass;

class NetworkStaticNatProperty implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $internalIp;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $wanName;

    /**
     * Returns Internal Ip.
     */
    public function getInternalIp(): ?string
    {
        return $this->internalIp;
    }

    /**
     * Sets Internal Ip.
     *
     * @maps internal_ip
     */
    public function setInternalIp(?string $internalIp): void
    {
        $this->internalIp = $internalIp;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Wan Name.
     * If not set, we configure the nat policies against all WAN ports for simplicity
     */
    public function getWanName(): ?string
    {
        return $this->wanName;
    }

    /**
     * Sets Wan Name.
     * If not set, we configure the nat policies against all WAN ports for simplicity
     *
     * @maps wan_name
     */
    public function setWanName(?string $wanName): void
    {
        $this->wanName = $wanName;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->internalIp)) {
            $json['internal_ip'] = $this->internalIp;
        }
        if (isset($this->name)) {
            $json['name']        = $this->name;
        }
        if (isset($this->wanName)) {
            $json['wan_name']    = $this->wanName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
