<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models;

use stdClass;

class ResponseSsoFailureSearchItem implements \JsonSerializable
{
    /**
     * @var string
     */
    private $detail;

    /**
     * @var string
     */
    private $samlAssertionXml;

    /**
     * @var float
     */
    private $timestamp;

    /**
     * @param string $detail
     * @param string $samlAssertionXml
     * @param float $timestamp
     */
    public function __construct(string $detail, string $samlAssertionXml, float $timestamp)
    {
        $this->detail = $detail;
        $this->samlAssertionXml = $samlAssertionXml;
        $this->timestamp = $timestamp;
    }

    /**
     * Returns Detail.
     */
    public function getDetail(): string
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     *
     * @required
     * @maps detail
     */
    public function setDetail(string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * Returns Saml Assertion Xml.
     */
    public function getSamlAssertionXml(): string
    {
        return $this->samlAssertionXml;
    }

    /**
     * Sets Saml Assertion Xml.
     *
     * @required
     * @maps saml_assertion_xml
     */
    public function setSamlAssertionXml(string $samlAssertionXml): void
    {
        $this->samlAssertionXml = $samlAssertionXml;
    }

    /**
     * Returns Timestamp.
     */
    public function getTimestamp(): float
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @required
     * @maps timestamp
     */
    public function setTimestamp(float $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['detail']             = $this->detail;
        $json['saml_assertion_xml'] = $this->samlAssertionXml;
        $json['timestamp']          = $this->timestamp;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
