<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib\Models;

use stdClass;

class ResponseSsoFailureSearch implements \JsonSerializable
{
    /**
     * @var ResponseSsoFailureSearchItem[]
     */
    private $results;

    /**
     * @param ResponseSsoFailureSearchItem[] $results
     */
    public function __construct(array $results)
    {
        $this->results = $results;
    }

    /**
     * Returns Results.
     *
     * @return ResponseSsoFailureSearchItem[]
     */
    public function getResults(): array
    {
        return $this->results;
    }

    /**
     * Sets Results.
     *
     * @required
     * @maps results
     *
     * @param ResponseSsoFailureSearchItem[] $results
     */
    public function setResults(array $results): void
    {
        $this->results = $results;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['results'] = $this->results;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
