<?php

declare(strict_types=1);

/*
 * MistAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MistAPILib;

/**
 * Environments available for API
 */
class Environment
{
    public const PRODUCTION = 'production';

    public const ENVIRONMENT2 = 'environment2';

    public const ENVIRONMENT3 = 'environment3';

    public const ENVIRONMENT4 = 'environment4';

    public const ENVIRONMENT5 = 'environment5';

    public const ENVIRONMENT6 = 'environment6';

    public const ENVIRONMENT7 = 'environment7';

    public const ENVIRONMENT8 = 'environment8';
}
